### ISSUE TITLE
Allow to specify `safeTxGas`

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-apps-sdk#21]
Often developers of dapps have a good understanding how much gas is required by their dapps. Therefore for normal transactions it is possible to provide the wallet with a `gasLimit` that should be used. For the Safe contracts `safeTxGas` is this gas limit. Therefore we should allow that a sapp can provide this information

**Comment by TomAFrench** [comment]
I'm running into issues with a safe app where metamask is estimating pretty much bang on the amount of gas required to complete and this is resulting in out-of-gas errors.

Here's an example of a failing and succeeding transaction.

failure (default gas limit): https://rinkeby.etherscan.io/tx/0x074eb6c5761f94892d0022de58a7f7db4633a0a082b4c5130dc64ffb1a3bf101
success (increased gas limit): https://rinkeby.etherscan.io/tx/0xe14bcf80174c845903dfcdc51af500feb40476d61816e8178249b2d060120fdf

I imagine that the root cause is that the 1/64th of gas which is reserved isn't being accounted for so while the overall transaction has enough gas it's just not in the right places.

I'm not really able to tell users increase their gas limits in metamask so being able to set a suggested gas limit which would be passed back to Gnosis Safe ui would be extremely useful in this situation.

**Comment by rmeissner** [comment]
This should be related to: https://github.com/gnosis/safe-react/issues/1048 as it seems that the tx submitted doesn't get any gas estimation (aka safeTxGas) at all (it is set to 0 in the transaction)
