### ISSUE TITLE
[bug] onTransactionConfirmation is called before safe transaction can be polled using the SDK

### ISSUE THREAD

**Issue by alaaltoros** [gnosis/safe-apps-sdk#61]
When trying to obtain the transaction details from the SDK calling `getBySafeTxHash` inside of `onTransactionConfirmation`, the object returned is always `{ detail: 'Not found' }`:

```javascript 
import initSdk, { SafeInfo } from "@gnosis.pm/safe-apps-sdk"

const appsSdk = initSdk()

const onTransactionConfirmation = ({ requestId, safeTxHash }) => {
  appsSdk.txs.getBySafeTxHash(e.safeTxHash).then((tx) => {
      console.log({ tx }) // { tx: { detail: 'Not found' } }
   })
};

appsSdk.addListeners({
  onTransactionConfirmation,
})
```
I worked around that by using setting a timeout, which is not ideal:
```javascript
setTimeout(() => appsSdk.txs.getBySafeTxHash(safeTxHash).then((safeTx) => {
   console.log({ safeTx }) // { safeTx: { safe: '0x...', ... } }
}), 2000)
```

However, the safeTx object returned has the property `transactionHash` equal to `null` and another (longer) setTimeout seems to be needed.

I recommend delaying the confirmation notification until the `transactionHash` exist, or alternatively adding another listener to track the transaction e.g. **onTransactionReady** or **onTransactionExecuted**

**Comment by mikheevm** [comment]
@alaaltoros 
This is kind of expected. The backend needs some time to index the transaction. We'll try to check if we can delay the onTransactionConfirmation event later to make it sure it's available.

> I recommend delaying the confirmation notification until the transactionHash exist, or alternatively adding another listener to track the transaction e.g. onTransactionReady or onTransactionExecuted

`transactionHash` prop corresponds to the hash of a transaction that executes the transaction. Since this is a multi-signature wallet, it may require some time for owners to confirm and execute a transaction. For now we expect app developers to maintain this, but we're working on improving that open to feature requests and feedback, so please feel free to ping us :)
